services:
  # PostgreSQL 資料庫
  postgres:
    image: postgres:15
    container_name: family_finance_db
    environment:
      POSTGRES_DB: family_finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: