[providers]
python = { runtime = "python-3.11" }

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn pangcah_accounting.wsgi:application --bind 0.0.0.0:${PORT:-8080}"