[providers]
python = { runtime = "python-3.11" }

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --settings=pangcah_accounting.settings.railway && python create_admin.py && python manage.py collectstatic --noinput --settings=pangcah_accounting.settings.railway && gunicorn pangcah_accounting.wsgi:application --bind 0.0.0.0:$PORT"