[providers]
python = { runtime = "python-3.11" }

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "echo 'DATABASE_URL=' $DATABASE_URL && echo 'All env vars:' && env | grep -E '(DATABASE|PG)' && DJANGO_SETTINGS_MODULE=family_finance.settings.railway python manage.py migrate && python manage.py collectstatic --noinput && DJANGO_SETTINGS_MODULE=family_finance.settings.railway gunicorn family_finance.wsgi:application --bind 0.0.0.0:$PORT"