# Generated by Django 5.0.1 on 2025-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "系統管理員"), ("USER", "一般用戶")],
                default="USER",
                help_text="用戶在系統中的角色",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
