# Generated by Django 5.0.1 on 2025-08-08 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "淺色主題"), ("dark", "深色主題")],
                        default="light",
                        max_length=10,
                        verbose_name="介面主題",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TWD", "新台幣"),
                            ("USD", "美元"),
                            ("EUR", "歐元"),
                            ("JPY", "日圓"),
                        ],
                        default="TWD",
                        max_length=3,
                        verbose_name="貨幣顯示",
                    ),
                ),
                (
                    "notifications",
                    models.BooleanField(default=True, verbose_name="應用內通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶偏好設定",
                "verbose_name_plural": "用戶偏好設定",
                "db_table": "user_preferences",
            },
        ),
    ]
