# Generated by Django 5.0.1 on 2025-08-07 12:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("events", "0001_initial"),
        ("groups", "0002_group_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="支出或收入金額",
                        max_digits=10,
                        verbose_name="金額",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("EXPENSE", "支出"), ("INCOME", "收入")],
                        default="EXPENSE",
                        help_text="支出或收入",
                        max_length=10,
                        verbose_name="類型",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(help_text="支出發生的日期時間", verbose_name="發生日期"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="支出的詳細描述", verbose_name="描述"
                    ),
                ),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        help_text="相關圖片 URL 列表",
                        size=None,
                        verbose_name="相關圖片",
                    ),
                ),
                # 注意：原本有 status、payment_status 和 paid_at 欄位
                # 已在後續的遷移中移除，個別支出記錄不再維護審批和付款狀態
                # 這些功能整合到最終活動結算階段統一處理
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="categories.category",
                        verbose_name="分類",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="events.event",
                        verbose_name="關聯活動",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="groups.group",
                        verbose_name="關聯群組",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="記錄者",
                    ),
                ),
            ],
            options={
                "verbose_name": "支出記錄",
                "verbose_name_plural": "支出記錄",
                "db_table": "expenses",
                "indexes": [
                    models.Index(fields=["type"], name="expenses_type_d84b61_idx"),
                    # 原 status 和 payment_status 的索引已移除
                    models.Index(fields=["date"], name="expenses_date_a77b87_idx"),
                ],
            },
        ),
    ]
