# Generated by Django 5.0.1 on 2025-08-07 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "split_type",
                    models.CharField(
                        choices=[
                            ("AVERAGE", "平均分攤"),
                            ("RATIO", "比例分攤"),
                            ("FIXED", "固定金額"),
                            ("SELECTIVE", "選擇性分攤"),
                        ],
                        default="AVERAGE",
                        help_text="費用的分攤計算方式",
                        max_length=20,
                        verbose_name="分攤類型",
                    ),
                ),
                (
                    "split_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="分攤的值（比例或固定金額）",
                        max_digits=10,
                        verbose_name="分攤值",
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="根據分攤方式計算出的實際金額",
                        max_digits=10,
                        verbose_name="計算後金額",
                    ),
                ),
                (
                    "is_adjusted",
                    models.BooleanField(
                        default=False, help_text="分攤是否被手動調整過", verbose_name="是否已調整"
                    ),
                ),
                (
                    "adjusted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="調整時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjusted_splits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="調整者",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="expenses.expense",
                        verbose_name="關聯支出",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_splits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分攤參與者",
                    ),
                ),
            ],
            options={
                "verbose_name": "費用分攤",
                "verbose_name_plural": "費用分攤",
                "db_table": "expense_splits",
                "indexes": [
                    models.Index(
                        fields=["expense", "participant"],
                        name="expense_spl_expense_296109_idx",
                    ),
                    models.Index(
                        fields=["split_type"], name="expense_spl_split_t_764666_idx"
                    ),
                    models.Index(
                        fields=["is_adjusted"], name="expense_spl_is_adju_668b21_idx"
                    ),
                ],
                "unique_together": {("expense", "participant")},
            },
        ),
    ]
