# Generated by Django 5.0.1 on 2025-08-07 12:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0002_group_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="活動的顯示名稱", max_length=200, verbose_name="活動名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="活動的詳細描述", verbose_name="活動描述"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="活動開始的日期時間", verbose_name="開始時間"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="活動結束的日期時間", verbose_name="結束時間"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "進行中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="ACTIVE",
                        help_text="活動目前的狀態",
                        max_length=10,
                        verbose_name="活動狀態",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="活動是否啟用", verbose_name="啟用狀態"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建此活動的用戶",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="創建者",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="活動所屬的群組",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="groups.group",
                        verbose_name="所屬群組",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動",
                "verbose_name_plural": "活動",
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="EDM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="EDM 的標題", max_length=200, verbose_name="EDM 標題"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="EDM 的詳細內容", verbose_name="EDM 內容"),
                ),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        help_text="EDM 相關圖片的 URL 列表",
                        size=None,
                        verbose_name="圖片列表",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        help_text="聯絡方式資訊",
                        max_length=500,
                        verbose_name="聯絡資訊",
                    ),
                ),
                (
                    "registration_link",
                    models.URLField(
                        blank=True, help_text="活動報名連結", verbose_name="報名連結"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edm",
                        to="events.event",
                        verbose_name="關聯活動",
                    ),
                ),
            ],
            options={
                "verbose_name": "EDM",
                "verbose_name_plural": "EDM",
                "db_table": "edms",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_status_8890b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["enabled"], name="events_enabled_4e318a_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_date"], name="events_start_d_6c01fc_idx"),
        ),
    ]
