# Generated by Django 5.0.1 on 2025-08-07 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="活動的總預算",
                max_digits=12,
                null=True,
                verbose_name="活動預算",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="活動是否已結算鎖定，鎖定後一般用戶無法新增記錄",
                verbose_name="結算鎖定狀態",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="可管理此活動的用戶列表",
                related_name="managed_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="活動管理者",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="settlement_date",
            field=models.DateTimeField(
                blank=True, help_text="活動結算的時間", null=True, verbose_name="結算時間"
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE_ADD", "新增支出"),
                            ("EXPENSE_EDIT", "編輯支出"),
                            ("EXPENSE_DELETE", "刪除支出"),
                            ("INCOME_ADD", "新增收入"),
                            ("INCOME_EDIT", "編輯收入"),
                            ("INCOME_DELETE", "刪除收入"),
                            ("USER_JOIN", "用戶加入"),
                            ("USER_LEAVE", "用戶離開"),
                            ("SPLIT_ADJUST", "調整分攤"),
                            ("STATUS_CHANGE", "狀態變更"),
                            ("ACTIVITY_EDIT", "活動編輯"),
                            ("SETTLEMENT", "執行結算"),
                        ],
                        help_text="執行的操作類型",
                        max_length=20,
                        verbose_name="操作類型",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="操作的詳細描述", verbose_name="操作描述"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作時間"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="操作的額外資訊，如變更前後的值",
                        verbose_name="操作元數據",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="events.event",
                        verbose_name="關聯活動",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動記錄",
                "verbose_name_plural": "活動記錄",
                "db_table": "activity_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["activity", "timestamp"],
                        name="activity_lo_activit_cc056e_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="activity_lo_action__9e4610_idx"
                    ),
                    models.Index(
                        fields=["operator"], name="activity_lo_operato_1d3f09_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="用戶加入活動的時間", verbose_name="加入時間"
                    ),
                ),
                (
                    "split_option",
                    models.CharField(
                        choices=[
                            ("NO_SPLIT", "不分攤先前費用"),
                            ("PARTIAL_SPLIT", "部分分攤費用"),
                            ("FULL_SPLIT", "分攤所有費用"),
                        ],
                        default="FULL_SPLIT",
                        help_text="用戶的費用分攤選項",
                        max_length=20,
                        verbose_name="分攤選項",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="用戶是否仍在活動中", verbose_name="是否活躍"
                    ),
                ),
                (
                    "partial_split_expenses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="當選擇部分分攤時，需要分攤的支出ID列表",
                        verbose_name="部分分攤支出列表",
                    ),
                ),
                (
                    "can_adjust_splits",
                    models.BooleanField(
                        default=False,
                        help_text="是否被授權可以調整費用分攤方式",
                        verbose_name="可調整分攤權限",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="events.event",
                        verbose_name="關聯活動",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="參與用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動參與者",
                "verbose_name_plural": "活動參與者",
                "db_table": "activity_participants",
                "indexes": [
                    models.Index(
                        fields=["activity", "user"],
                        name="activity_pa_activit_398ac3_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="activity_pa_is_acti_8510cf_idx"
                    ),
                ],
                "unique_together": {("activity", "user")},
            },
        ),
    ]
