# Generated by Django 5.0.1 on 2025-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_budget_event_is_locked_event_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_split",
            field=models.BooleanField(
                default=True, help_text="是否允許此活動的支出進行分帳", verbose_name="允許分帳"
            ),
        ),
    ]
