# Generated by Django 5.0 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_allow_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('EXPENSE_ADD', '新增支出'), ('EXPENSE_EDIT', '編輯支出'), ('EXPENSE_DELETE', '刪除支出'), ('INCOME_ADD', '新增收入'), ('INCOME_EDIT', '編輯收入'), ('INCOME_DELETE', '刪除收入'), ('USER_JOIN', '用戶加入'), ('USER_LEAVE', '用戶離開'), ('SPLIT_ADJUST', '調整分攤'), ('STATUS_CHANGE', '狀態變更'), ('ACTIVITY_EDIT', '活動編輯'), ('SETTLEMENT', '執行結算'), ('MANAGER_ADDED', '新增管理者'), ('MANAGER_REMOVED', '移除管理者')], help_text='執行的操作類型', max_length=30, verbose_name='操作類型'),
        ),
    ]