# Generated by Django 5.0.1 on 2025-08-07 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="被指定管理此群組的用戶",
                related_name="managed_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="群組管理者",
            ),
        ),
    ]
