# Generated by Django 5.0.1 on 2025-07-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="分類的顯示名稱", max_length=100, verbose_name="分類名稱"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("EXPENSE", "支出"), ("INCOME", "收入")],
                        help_text="分類是用於支出還是收入",
                        max_length=10,
                        verbose_name="分類類型",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="是否為系統預設分類", verbose_name="預設分類"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "分類",
                "verbose_name_plural": "分類",
                "db_table": "categories",
                "indexes": [
                    models.Index(fields=["type"], name="categories_type_735b1a_idx"),
                    models.Index(
                        fields=["is_default"], name="categories_is_defa_65fc70_idx"
                    ),
                ],
            },
        ),
    ]
